export const menuItems = [
  {
    to: "/",
    id: "home",
    cName: "menu-item",
    title: "Home",
    extern: false,
  },
  {
    to: "/#menu",
    id: "Menu",
    cName: "menu-item",
    title: "Menu",
    window:
      "https://drive.google.com/file/u/6/d/1TqVoihdQ-jPt-9s0msP35Gz-fyreB0p8/view?usp=sharing",
    extern: true,
  },
  {
    to: "/#location",
    id: "Location",
    cName: "menu-item",
    title: "Location",
    extern: false,
  },
  {
    to: "/#info",
    id: "contact",
    cName: "menu-item",
    title: "Contact",
    extern: false,
  },
  {
    to: "/Aboutus",
    id: "About-us",
    cName: "menu-item",
    title: "About Us",
    extern: false,
  },
  {
    to: "/bulk-order",
    id: "bulk-order",
    cName: "menu-item",
    title: "bulk-menu",
    extern: false,
  },
  {
    to: "route",
    id: "order-online",
    cName: "menu-item btn-outline",
    title: "Order-online",
    window: "https://www.zomato.com/mangalore/kebabci-1-kodailbail",
    extern: true,
  },
  {
    to: "route",
    id: "facebook",
    cName: "fab fa-facebook",
    extern: true,
  },
  {
    to: "route",
    id: "instagram",
    cName: "fab fa-instagram",
    window: "https://www.instagram.com/kebabci.mangalore/",
    extern: true,
  },
  {
    to: "route",
    id: "whatsapp",
    cName: "fab fa-whatsapp",
    window: "https://wa.me/919148044122",
    extern: true,
  },
];
export default menuItems;
